# Generated by Django 2.2.5 on 2019-09-29 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='code',
            field=models.CharField(default=0, max_length=36),
            preserve_default=False,
        ),
    ]
