# Generated by Django 2.2.5 on 2020-02-07 16:41

from django.db import migrations, models
import sitecelitel.utils


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='image_mobile',
            field=models.ImageField(blank=True, upload_to=sitecelitel.utils.get_photo, verbose_name='Изображение для телефона'),
        ),
        migrations.AddField(
            model_name='organization',
            name='image_tablet',
            field=models.ImageField(blank=True, upload_to=sitecelitel.utils.get_photo, verbose_name='Изображение для планшета'),
        ),
    ]
