# Generated by Django 2.2.5 on 2019-09-29 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_organization_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='address',
            field=models.CharField(blank=True, max_length=255, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='operating_mode',
            field=models.CharField(blank=True, max_length=255, verbose_name='График работы'),
        ),
    ]
