# Generated by Django 2.2.5 on 2019-11-17 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0005_auto_20190929_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='namefull',
            field=models.CharField(blank=True, max_length=255, verbose_name='Полное название'),
        ),
    ]
