# Generated by Django 2.2.5 on 2019-11-23 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0006_auto_20191117_1945'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Agreement',
        ),
    ]
