# Generated by Django 2.2.5 on 2019-11-22 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0006_auto_20191117_1945'),
        ('organization', '0006_auto_20191116_2048'),
    ]

    operations = [
    ]
