# Generated by Django 2.2.5 on 2019-11-23 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0005_auto_20191123_1438'),
        ('organization', '0007_delete_agreement'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agreement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=36)),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agreement', to='organization.Organization', verbose_name='Организация')),
                ('price_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agreement', to='service.PriceType', verbose_name='Тип цены')),
            ],
            options={
                'verbose_name': 'Соглашение',
                'verbose_name_plural': 'Соглашения',
                'db_table': 'agreements',
            },
        ),
    ]
