# Generated by Django 2.2.5 on 2019-11-30 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0014_auto_20191130_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agreement',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agreement', to='organization.Organization', verbose_name='Организация'),
        ),
    ]
