# Generated by Django 2.2.5 on 2020-01-03 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0001_initial'),
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='doctors',
            field=models.ManyToManyField(related_name='services', to='doctor.Doctor', verbose_name='Доктор(а)'),
        ),
    ]
