# Generated by Django 2.2.5 on 2019-11-15 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0006_auto_20191111_0039'),
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='doctors',
            field=models.ManyToManyField(related_name='services', to='doctor.Doctor', verbose_name='Доктор(а)'),
        ),
    ]
