# Generated by Django 2.2.5 on 2019-09-28 22:26

from django.db import migrations, models
import rusdoc.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RussianDoctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public', models.BooleanField(default=True, verbose_name='Публикация')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('preview', models.TextField(blank=True, verbose_name='Превью')),
                ('image', models.ImageField(blank=True, upload_to=rusdoc.models.get_photo, verbose_name='Изображение')),
                ('reception', models.BooleanField(default=True, verbose_name='Приём')),
            ],
            options={
                'verbose_name': 'Российский врач',
                'verbose_name_plural': 'Российские врачи',
                'db_table': 'russian_doctors',
            },
        ),
    ]
