# Generated by Django 2.2.5 on 2020-01-07 13:01

from django.db import migrations, models
import django.utils.timezone
import sitecelitel.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RussianDoctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public', models.BooleanField(default=True, verbose_name='Публикация')),
                ('created', models.DateField(default=django.utils.timezone.now, verbose_name='Дата создания')),
                ('updated', models.DateField(default=django.utils.timezone.now, verbose_name='Дата обновления')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('note', models.CharField(blank=True, max_length=100, verbose_name='Примечание')),
                ('preview', models.TextField(blank=True, verbose_name='Превью')),
                ('content', models.TextField(verbose_name='Контент')),
                ('image', models.ImageField(blank=True, upload_to=sitecelitel.utils.get_photo, verbose_name='Изображение')),
                ('capcha', models.CharField(blank=True, max_length=50, verbose_name='Подпись')),
                ('header', models.BooleanField(default=True, verbose_name='Показать в шапке')),
                ('data_start', models.DateField(verbose_name='Дата начала')),
                ('data_end', models.DateField(verbose_name='Дата конца')),
            ],
            options={
                'verbose_name': 'Российский врач',
                'verbose_name_plural': 'Российские врачи',
                'db_table': 'russian_doctors',
                'ordering': ['-data_start'],
            },
        ),
    ]
