# Generated by Django 2.2.5 on 2019-10-21 19:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('rusdoc', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='russiandoctor',
            name='created',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата создания'),
        ),
        migrations.AddField(
            model_name='russiandoctor',
            name='updated',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата обновления'),
        ),
    ]
