# Generated by Django 2.2.5 on 2019-11-10 22:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('rusdoc', '0002_auto_20191021_2230'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='russiandoctor',
            name='reception',
        ),
        migrations.AddField(
            model_name='russiandoctor',
            name='capcha',
            field=models.CharField(blank=True, max_length=50, verbose_name='Подпись'),
        ),
        migrations.AddField(
            model_name='russiandoctor',
            name='content',
            field=models.TextField(default=django.utils.timezone.now, verbose_name='Контент'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='russiandoctor',
            name='data_end',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата конца'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='russiandoctor',
            name='data_start',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата начала'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='russiandoctor',
            name='note',
            field=models.CharField(blank=True, max_length=100, verbose_name='Примечание'),
        ),
    ]
