# Generated by Django 2.2.5 on 2019-11-10 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rusdoc', '0003_auto_20191111_0143'),
    ]

    operations = [
        migrations.AddField(
            model_name='russiandoctor',
            name='header',
            field=models.BooleanField(default=True, verbose_name='Показать в шапке'),
        ),
    ]
