# Generated by Django 2.2.5 on 2020-01-07 17:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public', models.BooleanField(default=True, verbose_name='Публикация')),
                ('created', models.DateField(default=django.utils.timezone.now, verbose_name='Дата создания')),
                ('updated', models.DateField(default=django.utils.timezone.now, verbose_name='Дата обновления')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('preview', models.TextField(blank=True, verbose_name='Превью')),
                ('content', models.TextField(blank=True, verbose_name='Контент')),
                ('note', models.CharField(blank=True, max_length=255, null=True, verbose_name='Примечание')),
                ('data_start', models.DateField(blank=True, verbose_name='Дата начала')),
                ('data_end', models.DateField(blank=True, verbose_name='Дата конца')),
                ('header', models.BooleanField(default=True, verbose_name='Показать в шапке')),
            ],
            options={
                'verbose_name': 'Акция',
                'verbose_name_plural': 'Акции',
                'db_table': 'promotions',
                'ordering': ['-created'],
            },
        ),
    ]
