# Generated by Django 2.2.5 on 2019-09-28 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public', models.BooleanField(default=True, verbose_name='Публикация')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('preview', models.TextField(blank=True, verbose_name='Превью')),
                ('content', models.TextField(blank=True, verbose_name='Контент')),
                ('data_start', models.DateTimeField(blank=True, verbose_name='Дата начала')),
                ('data_end', models.DateTimeField(blank=True, verbose_name='Дата конца')),
                ('note', models.CharField(blank=True, max_length=255, null=True, verbose_name='Примечание')),
                ('doctor', models.ManyToManyField(blank=True, to='doctor.Doctor', verbose_name='Доктор')),
            ],
            options={
                'verbose_name': 'Акция',
                'verbose_name_plural': 'Акции',
                'db_table': 'promotions',
            },
        ),
    ]
