# Generated by Django 2.2.5 on 2019-09-29 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotion',
            name='data_end',
            field=models.DateField(blank=True, verbose_name='Дата конца'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='data_start',
            field=models.DateField(blank=True, verbose_name='Дата начала'),
        ),
    ]
