# Generated by Django 2.2.5 on 2019-10-21 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotion', '0002_auto_20190929_1621'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotion',
            name='header',
            field=models.BooleanField(default=True, verbose_name='Показать в шапке'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='doctor',
            field=models.ManyToManyField(blank=True, related_name='promotions', to='doctor.Doctor', verbose_name='Доктор'),
        ),
    ]
