# Generated by Django 2.2.5 on 2019-11-11 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('promotion', '0003_auto_20191021_2230'),
        ('promotion', '0003_auto_20191021_1452'),
    ]

    operations = [
    ]
