# Generated by Django 2.2.5 on 2019-11-16 17:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('promotion', '0004_merge_20191111_1502'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotion',
            name='created',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата создания'),
        ),
    ]
