# Generated by Django 2.2.5 on 2019-09-28 15:43

import article.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public', models.BooleanField(default=True, verbose_name='Публикация')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Уникальное имя')),
                ('preview', models.TextField(blank=True, null=True, verbose_name='Превью')),
                ('content', models.TextField(blank=True, null=True, verbose_name='Контент')),
                ('created', models.DateField(auto_now_add=True)),
                ('update', models.DateField(auto_now=True)),
                ('image', models.ImageField(blank=True, upload_to=article.models.get_photo, verbose_name='Изображение')),
                ('doctor', models.ManyToManyField(related_name='article', to='doctor.Doctor', verbose_name='Доктор')),
            ],
            options={
                'verbose_name': 'Статья',
                'verbose_name_plural': 'Статьи',
                'db_table': 'article',
            },
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like', models.PositiveIntegerField(default=0)),
                ('dislike', models.PositiveIntegerField(default=0)),
                ('article', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rating', to='article.Article')),
            ],
            options={
                'db_table': 'rating',
            },
        ),
    ]
