# Generated by Django 2.2.5 on 2019-09-29 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='doctor',
            field=models.ManyToManyField(blank=True, related_name='article', to='doctor.Doctor', verbose_name='Доктор'),
        ),
    ]
