# Generated by Django 2.2.5 on 2019-09-30 07:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0002_auto_20190929_0125'),
        ('article', '0002_auto_20190929_1630'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='doctor',
        ),
        migrations.AddField(
            model_name='article',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='article', to='doctor.Doctor', verbose_name='Доктор'),
        ),
    ]
