# Generated by Django 2.2.5 on 2019-10-19 20:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tag', '0001_initial'),
        ('article', '0004_auto_20190930_1637'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='articles', to='tag.ArticleTag', verbose_name='Статьи'),
        ),
        migrations.AlterField(
            model_name='article',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='article', to='doctor.Doctor', verbose_name='Доктор'),
        ),
    ]
