# Generated by Django 2.2.5 on 2019-10-21 19:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0005_auto_20191019_2351'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='update',
        ),
        migrations.AddField(
            model_name='article',
            name='updated',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='article',
            name='created',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='article',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='articles', to='tag.ArticleTag', verbose_name='Теги'),
        ),
    ]
