# Generated by Django 2.2.5 on 2019-11-12 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0008_article_header'),
        ('article', '0007_merge_20191111_1502'),
    ]

    operations = [
    ]
