# Generated by Django 2.2.5 on 2019-11-22 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0009_about'),
        ('article', '0009_merge_20191112_1457'),
    ]

    operations = [
    ]
