# Generated by Django 2.2.5 on 2019-10-20 10:54

from django.db import migrations, models
import django.utils.timezone
import sitecelitel.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctor', '0003_doctor_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='New',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public', models.BooleanField(default=True, verbose_name='Публикация')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('preview', models.TextField(verbose_name='Превью')),
                ('content', models.TextField(verbose_name='Контент')),
                ('image', models.ImageField(upload_to=sitecelitel.utils.get_photo, verbose_name='Изображение')),
                ('caption', models.CharField(max_length=255, verbose_name='Подпись')),
                ('created', models.DateField(default=django.utils.timezone.now, verbose_name='Дата создания')),
                ('update', models.DateField(default=django.utils.timezone.now, verbose_name='Дата обновления')),
                ('doctors', models.ManyToManyField(blank=True, related_name='news', to='doctor.Doctor', verbose_name='Доктора')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
                'db_table': 'news',
            },
        ),
    ]
