# Generated by Django 2.2.5 on 2019-10-20 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='new',
            old_name='update',
            new_name='updated',
        ),
        migrations.AddField(
            model_name='new',
            name='header',
            field=models.BooleanField(default=True, verbose_name='Показать в шапке'),
        ),
    ]
