# Generated by Django 2.2.5 on 2019-09-28 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public', models.BooleanField(default=True, verbose_name='Публикация')),
                ('specialization', models.CharField(max_length=255, verbose_name='Специализация')),
                ('city', models.CharField(max_length=255, verbose_name='Город')),
                ('position', models.CharField(max_length=255, verbose_name='Позиция')),
                ('duty', models.TextField(blank=True, verbose_name='Обязанность')),
                ('requiremen', models.TextField(blank=True, verbose_name='Требование')),
                ('condition', models.TextField(blank=True, verbose_name='Условие')),
                ('phone', models.CharField(blank=True, max_length=45, verbose_name='Телефон')),
                ('email', models.CharField(blank=True, max_length=45, verbose_name='Email')),
            ],
            options={
                'verbose_name': 'Вакансия',
                'verbose_name_plural': 'Вакансии',
                'db_table': 'vacancies',
            },
        ),
    ]
