# Generated by Django 2.2.5 on 2019-11-21 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vacancy', '0002_auto_20191021_2230'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Группа вакансии',
                'verbose_name_plural': 'Группы вакансий',
                'db_table': 'groups_vacancies',
            },
        ),
        migrations.RemoveField(
            model_name='vacancy',
            name='condition',
        ),
        migrations.RemoveField(
            model_name='vacancy',
            name='duty',
        ),
        migrations.RemoveField(
            model_name='vacancy',
            name='requiremen',
        ),
        migrations.AddField(
            model_name='vacancy',
            name='content',
            field=models.TextField(blank=True, verbose_name='Контент'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='vacancy.Group', verbose_name='Группа'),
        ),
    ]
