# Generated by Django 2.2.5 on 2019-11-21 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vacancy', '0003_auto_20191121_1335'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacancy',
            name='specialization',
        ),
    ]
