# Generated by Django 2.2.5 on 2019-11-21 12:33

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('vacancy', '0004_remove_vacancy_specialization'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='created',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата создания'),
        ),
        migrations.AddField(
            model_name='group',
            name='public',
            field=models.BooleanField(default=True, verbose_name='Публикация'),
        ),
        migrations.AddField(
            model_name='group',
            name='updated',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='vacancies', to='vacancy.Group', verbose_name='Группа'),
        ),
    ]
