# Generated by Django 2.2.5 on 2019-10-19 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public', models.BooleanField(default=True, verbose_name='Публикация')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('header', models.BooleanField(default=True, verbose_name='Показать в шапке')),
            ],
            options={
                'db_table': 'articletag',
            },
        ),
        migrations.CreateModel(
            name='DoctorTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public', models.BooleanField(default=True, verbose_name='Публикация')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('header', models.BooleanField(default=True, verbose_name='Показать в шапке')),
            ],
            options={
                'db_table': 'doctortag',
            },
        ),
    ]
