# Generated by Django 2.2.5 on 2020-01-07 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public', models.BooleanField(default=True, verbose_name='Публикация')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Уникальное имя')),
                ('header', models.BooleanField(default=True, verbose_name='Показать в шапке')),
            ],
            options={
                'verbose_name': 'Тег статьи',
                'verbose_name_plural': 'Теги статей',
                'db_table': 'articletag',
            },
        ),
        migrations.CreateModel(
            name='DoctorTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public', models.BooleanField(default=True, verbose_name='Публикация')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Уникальное имя')),
                ('header', models.BooleanField(default=True, verbose_name='Показать в шапке')),
            ],
            options={
                'verbose_name': 'Тег доктора',
                'verbose_name_plural': 'Теги докторов',
                'db_table': 'doctortag',
            },
        ),
    ]
