# Generated by Django 2.2.5 on 2019-10-20 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tag', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articletag',
            options={'verbose_name': 'Тег статьи', 'verbose_name_plural': 'Теги статей'},
        ),
        migrations.AlterModelOptions(
            name='doctortag',
            options={'verbose_name': 'Тег доктора', 'verbose_name_plural': 'Теги докторов'},
        ),
        migrations.AddField(
            model_name='articletag',
            name='slug',
            field=models.SlugField(default=0, max_length=255, verbose_name='Уникальное имя'),
        ),
        migrations.AddField(
            model_name='doctortag',
            name='slug',
            field=models.SlugField(default=0, max_length=255, verbose_name='Уникальное имя'),
        ),
    ]
