# Generated by Django 2.2.5 on 2019-10-20 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tag', '0002_auto_20191020_1232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articletag',
            name='slug',
            field=models.SlugField(max_length=255, unique=True, verbose_name='Уникальное имя'),
        ),
        migrations.AlterField(
            model_name='doctortag',
            name='slug',
            field=models.SlugField(max_length=255, unique=True, verbose_name='Уникальное имя'),
        ),
    ]
