# Generated by Django 2.2.5 on 2020-01-07 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='public',
            field=models.BooleanField(default=True, verbose_name='Публикация'),
        ),
    ]
