# Generated by Django 2.2.5 on 2020-01-08 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0002_slider_public'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='slider',
            options={'ordering': ['title', 'id'], 'verbose_name': 'Слайдер', 'verbose_name_plural': 'Слайдер'},
        ),
        migrations.AddField(
            model_name='slider',
            name='order',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='Сортировка'),
        ),
    ]
