# Generated by Django 2.2.5 on 2020-01-08 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0003_auto_20200108_2122'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='slider',
            options={'ordering': ['-order'], 'verbose_name': 'Слайдер', 'verbose_name_plural': 'Слайдер'},
        ),
    ]
