# Generated by Django 2.2.5 on 2020-01-12 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0004_auto_20200108_2149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slider',
            name='url',
            field=models.CharField(blank=True, help_text='Пример: /article/about/', max_length=500, verbose_name='URL'),
        ),
    ]
