# Generated by Django 2.2.5 on 2020-01-12 13:03

import clinic.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0005_auto_20200112_1443'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public', models.BooleanField(default=True, verbose_name='Публикация')),
                ('name', models.CharField(db_index=True, max_length=500, verbose_name='Название')),
                ('url', models.URLField(verbose_name='URL')),
                ('logo', models.FileField(upload_to=clinic.utils.get_image_partner, verbose_name='logo')),
                ('order', models.PositiveIntegerField(blank=True, default=0, verbose_name='Сортировка')),
            ],
            options={
                'verbose_name': 'Партнер',
                'verbose_name_plural': 'Партнеры',
                'db_table': 'partners',
                'ordering': ['-order'],
            },
        ),
    ]
