# Generated by Django 2.2.5 on 2020-02-08 09:01

import clinic.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0006_partner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public', models.BooleanField(default=True, verbose_name='Публикация')),
                ('title', models.CharField(max_length=500, verbose_name='Название')),
                ('url', models.CharField(blank=True, max_length=500, verbose_name='URL')),
                ('image_one', models.ImageField(blank=True, upload_to=clinic.utils.get_image_pc, verbose_name='Изображение для шапки 1')),
                ('image_two', models.ImageField(blank=True, upload_to=clinic.utils.get_image_pc, verbose_name='Изображение для шапки 2')),
                ('image_three', models.ImageField(blank=True, upload_to=clinic.utils.get_image_pc, verbose_name='Изображение для шапки 3')),
                ('description', models.TextField(blank=True, verbose_name='Текст на шапке')),
                ('content', models.TextField(blank=True, verbose_name='Текст')),
                ('image_full', models.ImageField(blank=True, upload_to=clinic.utils.get_image_pc, verbose_name='Изображение для страницы')),
            ],
            options={
                'verbose_name': 'Стационар',
                'verbose_name_plural': 'Стационар',
                'db_table': 'hospital',
                'ordering': ['-title'],
            },
        ),
    ]
