# Generated by Django 2.2.5 on 2020-02-19 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0008_auto_20200219_1106'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalCertificates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public', models.BooleanField(default=True, verbose_name='Публикация')),
                ('title', models.CharField(max_length=500, verbose_name='Название')),
                ('url', models.SlugField(blank=True, max_length=500, verbose_name='URL')),
                ('content', models.TextField(blank=True, verbose_name='Текст')),
            ],
            options={
                'verbose_name': 'Медицинская справка',
                'verbose_name_plural': 'Медицинские справки',
                'db_table': 'medicalCertificates',
                'ordering': ['-title'],
            },
        ),
    ]
