# Generated by Django 2.2.5 on 2020-01-03 15:59

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import sitecelitel.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public', models.BooleanField(default=True, verbose_name='Публикация')),
                ('created', models.DateField(default=django.utils.timezone.now, verbose_name='Дата создания')),
                ('updated', models.DateField(default=django.utils.timezone.now, verbose_name='Дата обновления')),
                ('code', models.CharField(max_length=11)),
                ('main_code', models.CharField(blank=True, max_length=11)),
                ('full_name', models.CharField(blank=True, max_length=255, verbose_name='Полное имя')),
                ('gender', models.CharField(blank=True, choices=[('м', 'Мужчина'), ('ж', 'Женщина'), ('н', 'Нет пола')], default='н', max_length=1, verbose_name='Пол')),
                ('childish', models.BooleanField(default=False, verbose_name='Детский доктор')),
                ('adult', models.BooleanField(default=False, verbose_name='Взрослый доктор')),
                ('photo', models.ImageField(blank=True, upload_to=sitecelitel.utils.get_photo, verbose_name='Фото')),
                ('avatar', models.ImageField(blank=True, upload_to=sitecelitel.utils.get_photo, verbose_name='Аватарка')),
                ('experience', models.CharField(blank=True, max_length=45, verbose_name='Опыт')),
                ('academic_degree', models.CharField(blank=True, max_length=100, verbose_name='Ученая степень')),
                ('content', models.TextField(blank=True, verbose_name='Контент')),
                ('special_note', models.TextField(blank=True, null=True, verbose_name='Примечание')),
                ('department', models.ManyToManyField(blank=True, related_name='department', to='organization.Department', verbose_name='Депортамент')),
            ],
            options={
                'verbose_name': 'Доктор',
                'verbose_name_plural': 'Доктора',
                'db_table': 'doctors',
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='DoctorTiming',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dates', to='doctor.Doctor', verbose_name='Доктор')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doc_timing', to='organization.Organization', verbose_name='Организация')),
            ],
            options={
                'verbose_name': 'Приём',
                'verbose_name_plural': 'Приёмы',
                'db_table': 'doctor_dates',
            },
        ),
        migrations.CreateModel(
            name='Specialization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=36)),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Специялизация',
                'verbose_name_plural': 'Специализации',
                'db_table': 'specialization',
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public', models.BooleanField(default=True, verbose_name='Публикация')),
                ('created', models.DateField(default=django.utils.timezone.now, verbose_name='Дата создания')),
                ('updated', models.DateField(default=django.utils.timezone.now, verbose_name='Дата обновления')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('video', models.TextField(verbose_name='Видео')),
                ('doctor', models.ManyToManyField(related_name='videos', to='doctor.Doctor', verbose_name='Доктор(а)')),
            ],
            options={
                'verbose_name': 'Видео',
                'verbose_name_plural': 'Видео',
                'db_table': 'video',
            },
        ),
        migrations.CreateModel(
            name='Timing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.CharField(blank=True, max_length=5, verbose_name='Начало')),
                ('end', models.CharField(blank=True, max_length=5, verbose_name='Конец')),
                ('free', models.BooleanField(default=0, verbose_name='Статус')),
                ('date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timing', to='doctor.DoctorTiming', verbose_name='Дата приема')),
            ],
            options={
                'verbose_name': 'Время приема',
                'verbose_name_plural': 'Часы приема',
                'db_table': 'doctor_times',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public', models.BooleanField(default=True, verbose_name='Публикация')),
                ('created', models.DateField(default=django.utils.timezone.now, verbose_name='Дата создания')),
                ('updated', models.DateField(default=django.utils.timezone.now, verbose_name='Дата обновления')),
                ('author', models.CharField(max_length=255, verbose_name='Автор')),
                ('review', models.TextField(verbose_name='Отзыв')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='doctor.Doctor', verbose_name='Доктор')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
                'db_table': 'reviews',
            },
        ),
        migrations.AddField(
            model_name='doctor',
            name='specialization',
            field=models.ManyToManyField(blank=True, related_name='doctor', to='doctor.Specialization', verbose_name='Специализация'),
        ),
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=45, verbose_name='Название')),
                ('question', models.TextField(blank=True, verbose_name='Вопрос')),
                ('answer', models.TextField(blank=True, verbose_name='Ответ')),
                ('status', models.BooleanField(default=False, verbose_name='Статус')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('date_quest', models.DateTimeField(auto_now_add=True, verbose_name='Дата вопроса')),
                ('date_answer', models.DateTimeField(auto_now=True, verbose_name='Дата ответа')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultation', to='doctor.Doctor', verbose_name='Доктор')),
            ],
            options={
                'verbose_name': 'Консультация',
                'verbose_name_plural': 'Консультации',
                'db_table': 'consultation',
            },
        ),
    ]
