# Generated by Django 2.2.5 on 2019-09-28 22:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='consultation',
            old_name='done',
            new_name='status',
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public', models.BooleanField(default=True, verbose_name='Публикация')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('video', models.TextField(verbose_name='Видео')),
                ('doctor', models.ManyToManyField(related_name='video', to='doctor.Doctor', verbose_name='Доктор(а)')),
            ],
            options={
                'verbose_name': 'Видео',
                'verbose_name_plural': 'Видео',
                'db_table': 'video',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public', models.BooleanField(default=True, verbose_name='Публикация')),
                ('author', models.CharField(max_length=255, verbose_name='Автор')),
                ('review', models.TextField(verbose_name='Отзыв')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='doctor.Doctor', verbose_name='Доктор')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
                'db_table': 'reviews',
            },
        ),
    ]
