# Generated by Django 2.2.5 on 2019-10-19 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tag', '0001_initial'),
        ('doctor', '0002_auto_20190929_0125'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='doctors', to='tag.DoctorTag', verbose_name='Доктор(а)'),
        ),
    ]
