# Generated by Django 2.2.5 on 2020-02-02 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0002_doctor_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='the_best',
            field=models.BooleanField(blank=True, default=True, verbose_name='Доктор дня'),
        ),
    ]
