# Generated by Django 2.2.5 on 2020-02-02 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0003_doctor_the_best'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='the_best',
            field=models.BooleanField(blank=True, default=False, verbose_name='Доктор дня'),
        ),
    ]
