# Generated by Django 2.2.5 on 2019-10-27 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0004_auto_20191021_2230'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='tags',
        ),
    ]
