# Generated by Django 2.2.5 on 2019-11-10 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0005_remove_doctor_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='doctor',
            field=models.ManyToManyField(related_name='videos', to='doctor.Doctor', verbose_name='Доктор(а)'),
        ),
    ]
