# Generated by Django 2.2.5 on 2019-11-17 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0006_auto_20191111_0039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='full_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Полное имя'),
        ),
    ]
