# Generated by Django 2.2.5 on 2019-11-17 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0006_auto_20191117_1945'),
        ('doctor', '0007_auto_20191117_1945'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='doctortiming',
            table='doctor_dates',
        ),
        migrations.CreateModel(
            name='Timing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hour', models.CharField(default=0, max_length=5, verbose_name='Время приема')),
                ('date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timing', to='doctor.DoctorTiming', verbose_name='Дата приема')),
            ],
            options={
                'verbose_name': 'Время приема',
                'verbose_name_plural': 'Часы приема',
                'db_table': 'doctor_times',
            },
        ),
    ]
