# Generated by Django 2.2.5 on 2019-11-21 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0006_auto_20191117_1945'),
        ('doctor', '0008_auto_20191117_1955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctortiming',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dates', to='doctor.Doctor', verbose_name='Доктор'),
        ),
    ]
