# Generated by Django 2.2.5 on 2019-11-22 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0007_auto_20191116_2048'),
        ('doctor', '0009_auto_20191121_1335'),
    ]

    operations = [
    ]
