# Generated by Django 2.2.5 on 2019-11-23 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0006_auto_20191117_1945'),
        ('doctor', '0009_auto_20191121_1335'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctortiming',
            name='active',
        ),
        migrations.RemoveField(
            model_name='doctortiming',
            name='time_end',
        ),
        migrations.RemoveField(
            model_name='doctortiming',
            name='time_start',
        ),
        migrations.AddField(
            model_name='doctor',
            name='organization',
            field=models.ManyToManyField(related_name='doctors', to='organization.Organization', verbose_name='Организация'),
        ),
        migrations.AddField(
            model_name='doctortiming',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='doc_timing', to='organization.Organization', verbose_name='Организация'),
        ),
    ]
