# Generated by Django 2.2.5 on 2019-11-23 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0010_auto_20191123_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctortiming',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doc_timing', to='organization.Organization', verbose_name='Организация'),
        ),
    ]
