# Generated by Django 2.2.5 on 2019-11-24 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0011_auto_20191123_1710'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='specialization',
        ),
        migrations.AddField(
            model_name='doctor',
            name='specialization',
            field=models.ManyToManyField(blank=True, related_name='doctor', to='doctor.Specialization', verbose_name='Специализация'),
        ),
    ]
