# Generated by Django 2.2.5 on 2019-11-26 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0013_doctor_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='adult',
            field=models.BooleanField(default=False, verbose_name='Взрослый доктор'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='childish',
            field=models.BooleanField(default=False, verbose_name='Детский доктор'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='gender',
            field=models.CharField(blank=True, choices=[('m', 'Мужчина'), ('w', 'Женщина'), ('n', 'Нет пола')], default='n', max_length=1, verbose_name='Пол'),
        ),
    ]
