# Generated by Django 2.2.5 on 2019-11-27 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0012_auto_20191123_1939'),
        ('doctor', '0014_auto_20191126_2258'),
    ]

    operations = [
    ]
