# Generated by Django 2.2.5 on 2019-12-01 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0014_auto_20191126_2258'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doctor',
            options={'ordering': ['-id'], 'verbose_name': 'Доктор', 'verbose_name_plural': 'Доктора'},
        ),
        migrations.AddField(
            model_name='timing',
            name='free',
            field=models.BooleanField(default=0, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='gender',
            field=models.CharField(blank=True, choices=[('м', 'Мужчина'), ('ж', 'Женщина'), ('н', 'Нет пола')], default='н', max_length=1, verbose_name='Пол'),
        ),
    ]
