# Generated by Django 2.2.5 on 2019-12-01 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0015_merge_20191127_2026'),
        ('doctor', '0015_auto_20191201_0544'),
    ]

    operations = [
    ]
