# Generated by Django 2.2.5 on 2019-12-02 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0015_auto_20191201_0544'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timing',
            name='hour',
        ),
        migrations.AddField(
            model_name='timing',
            name='end',
            field=models.CharField(default=0, max_length=5, verbose_name='Конец'),
        ),
        migrations.AddField(
            model_name='timing',
            name='start',
            field=models.CharField(default=0, max_length=5, verbose_name='Начало'),
        ),
    ]
