# Generated by Django 2.2.5 on 2019-12-02 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0016_merge_20191201_1343'),
        ('doctor', '0016_auto_20191202_2004'),
    ]

    operations = [
    ]
