# Generated by Django 2.2.5 on 2019-09-28 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0002_auto_20190928_1901'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faq',
            name='active',
        ),
    ]
